IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'TODOLISTSQL')
BEGIN
    CREATE DATABASE TODOLISTSQL;
END
GO


ALTER LOGIN sa ENABLE;
ALTER LOGIN sa WITH PASSWORD = 'password';
GO


ALTER AUTHORIZATION ON DATABASE::TODOLISTSQL TO sa;
GO
